### ISSUE TITLE
Point class in Python bindings doesn't support non-string keys

### ISSUE THREAD

**Issue by gentlecat** [MTG/gaia#24] opened 2015-08-11 15:39 UTC
See first two exceptions in this example:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)                                                                                             
[GCC 4.8.2] on linux2                                                                                                                     
Type "help", "copyright", "credits" or "license" for more information.                                                                    
>>> import gaia2                                                                                                                          
>>> p = gaia2.Point()                                                                                                                     
>>> p[unicode("hello")] = "test"                                                                                                          
Traceback (most recent call last):                                                                                                        
  File "<stdin>", line 1, in <module>                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 4677, in autoSetValue                                             
    p.setLabel(name, value)                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 3546, in setLabel                                                 
    return _gaia2.Point_setLabel(self, *args)                                                                                             
NotImplementedError: Wrong number or type of arguments for overloaded function 'Point_setLabel'.                                          
  Possible C/C++ prototypes are:                                                                                                          
    gaia2::Point::setLabel(QString const &,gaia2::StringDescriptor const &)                                                               
    gaia2::Point::setLabel(int,QString const &,gaia2::StringDescriptor const &)                                                           
    gaia2::Point::setLabel(std::string const &,gaia2::StringDescriptor const &)                                                           
    gaia2::Point::setLabel(int,std::string const &,gaia2::StringDescriptor const &)                                                       
    gaia2::Point::setLabel(std::string const &,std::vector< std::string,std::allocator< std::string > > const &)                          
    gaia2::Point::setLabel(int,std::string const &,std::vector< std::string,std::allocator< std::string > > const &)                      
    gaia2::Point::setLabel(std::string const &,std::string const &)                                                                       
    gaia2::Point::setLabel(int,std::string const &,std::string const &)                                                                   

>>> p[0] = "test"                                                                                                                         
Traceback (most recent call last):                                                                                                        
  File "<stdin>", line 1, in <module>                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 4677, in autoSetValue                                             
    p.setLabel(name, value)                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 3546, in setLabel                                                 
    return _gaia2.Point_setLabel(self, *args)                                                                                             
NotImplementedError: Wrong number or type of arguments for overloaded function 'Point_setLabel'.                                          
  Possible C/C++ prototypes are:                                                                                                          
    gaia2::Point::setLabel(QString const &,gaia2::StringDescriptor const &)                                                               
    gaia2::Point::setLabel(int,QString const &,gaia2::StringDescriptor const &)                                                           
    gaia2::Point::setLabel(std::string const &,gaia2::StringDescriptor const &)                                                           
    gaia2::Point::setLabel(int,std::string const &,gaia2::StringDescriptor const &)                                                       
    gaia2::Point::setLabel(std::string const &,std::vector< std::string,std::allocator< std::string > > const &)                          
    gaia2::Point::setLabel(int,std::string const &,std::vector< std::string,std::allocator< std::string > > const &)                      
    gaia2::Point::setLabel(std::string const &,std::string const &)                                                                       
    gaia2::Point::setLabel(int,std::string const &,std::string const &)                                                                   

>>> p["test"] = "test"                                                                                                                    
Traceback (most recent call last):                                                                                                        
  File "<stdin>", line 1, in <module>                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 4677, in autoSetValue                                             
    p.setLabel(name, value)                                                                                                               
  File "/usr/local/lib/python2.7/dist-packages/gaia2/__init__.py", line 3546, in setLabel                                                 
    return _gaia2.Point_setLabel(self, *args)                                                                                             
Exception: Couldn't find node with name 'test'                                                                                            
>>>
```

**Comment by dbogdanov** [comment] 2018-04-19 09:57
Non-string keys would make sense if we had regression models, but we only have classifier models for now, therefore, closing this issue.

**Comment by alastair** [comment] 2018-04-20 06:52
Note that in this case "non-string" can also mean "unicode" - the numerical example was just to compare and see that it's the same error as when passing unicode. Do we want to override setLabel to allow unicode as well, or document that the API takes only byte/ascii values?

**Comment by sildeag** [comment] 2018-04-20 16:03
This discussion could wait until after implementing Python3 as well as Python2.
With Python3
`>>> from past.builtins import unicode`
`>>> p[unicode("hello")] = "test"`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/local/lib/python3.6/dist-packages/gaia2/__init__.py", line 6323, in autoSetValue`
`    p.setLabel(name, value)`
`  File "/usr/local/lib/python3.6/dist-packages/gaia2/__init__.py", line 5002, in setLabel`
`    return _gaia2.Point_setLabel(self, *args)`
`Exception: Couldn't find node with name 'hello'`

**Comment by alastair** [comment] 2021-12-22 12:20
No longer a problem since we're finally supporting only python3

**Closed by alastair** 2021-12-22 12:20 UTC
