### ISSUE TITLE
Build failed on osx yosemite "Error: Unknown SWIG preprocessor directive"

### ISSUE THREAD

**Issue by erikparr** [MTG/gaia#23] opened 2015-07-31 10:05 UTC
I am trying to install on yosemite, but keep failing to build. I tried ./waf clean and configuring again but i get the following errors:

[ 85/104] swig: src/bindings/gaia.swig -> build/src/bindings/gaia2.swigwrap_1.cxx build/src/bindings/gaia2.py
../src/bindings/frozendataset.i:57: Error: Unknown SWIG preprocessor directive: try (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:14: Error: Unknown SWIG preprocessor directive: shortcut (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:27: Error: Unknown SWIG preprocessor directive: until (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:42: Error: Unknown SWIG preprocessor directive: converts (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:52: Error: Unknown SWIG preprocessor directive: useful (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:56: Error: Unknown SWIG preprocessor directive: oh (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:57: Error: Unknown SWIG preprocessor directive: but (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:58: Error: Unknown SWIG preprocessor directive: FilterWrapper (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:61: Error: Unknown SWIG preprocessor directive: make (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:71: Error: Unknown SWIG preprocessor directive: make (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:92: Error: Unknown SWIG preprocessor directive: complete (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:127: Error: Unknown SWIG preprocessor directive: args (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:190: Error: Unknown SWIG preprocessor directive: print (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:203: Error: Unknown SWIG preprocessor directive: remove (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:220: Error: Unknown SWIG preprocessor directive: automatic (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:223: Error: Unknown SWIG preprocessor directive: real (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:231: Error: Unknown SWIG preprocessor directive: commutativity (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:235: Error: Unknown SWIG preprocessor directive: string (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:241: Error: Unknown SWIG preprocessor directive: enhanced (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:243: Error: Unknown SWIG preprocessor directive: should (if this is a block of target language code, delimit it with %{ and %})
../src/bindings/pythonic.i:244: Error: Unknown SWIG preprocessor directive: reach (if this is a block of target language code, delimit it with %{ and %})
Waf: Leaving directory `/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build'

Build failed
 -> task in '_gaia2' failed (exit status 1): 
	{task 4345091344: swig gaia.swig -> gaia2.swigwrap_1.cxx,gaia2.py}
['/usr/local/bin/swig', '-c++', '-python', '-w451', '-o', '/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build/src/bindings/gaia2.swigwrap_1.cxx', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build/src', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/src', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build/src/bindings', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/src/bindings', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build/src/metrics', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/src/metrics', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/build/src/3rdparty', '-I/Users/erikparr/Documents/_Projects/freesound-python-master/gaia-master/src/3rdparty', '-I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7', '-I/usr/local/Cellar/qt/4.8.7/include', '-I/usr/local/Cellar/qt/4.8.7/include/QtCore', '-I/usr/local/Cellar/qt/4.8.7/include/QtNetwork', '-DGAIA_VERSION="2.4.4"', '-DGAIA_GIT_SHA="Undefined"', '-DHAVE_QTUITOOLS_DEBUG=1', '-DHAVE_QTCORE=1', '-DHAVE_QTGUI=1', '-DHAVE_QTUITOOLS=1', '-DHAVE_QTNETWORK=1', '-DHAVE_QTOPENGL=1', '-DHAVE_QTSQL=1', '-DHAVE_QTSVG=1', '-DHAVE_QTTEST=1', '-DHAVE_QTXML=1', '-DHAVE_QTXMLPATTERNS=1', '-DHAVE_QTWEBKIT=1', '-DHAVE_QTHELP=1', '-DHAVE_QTSCRIPT=1', '-DHAVE_QTDECLARATIVE=1', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DHAVE_PYTHON_H=1', '-DNDEBUG', '-DQT_SHARED', '-DQT_SHARED', '../src/bindings/gaia.swig']

**Comment by alastair** [comment] 2015-08-02 10:05
Duplicate of #13

**Closed by alastair** 2015-08-02 10:05 UTC

**Comment by alastair** [comment] 2015-08-02 10:49
Fixed in 2fa9922252f07fe84e67e67c18cf947868b61795
